openapi: 3.0.2
info:
  title: Bugzilla OpenAPI
  description: OpenAPI definitions for Bugzilla's REST API
  version: 0.0.1
externalDocs:
  description: Bugzilla API Documentation
  url: https://bugzilla.readthedocs.io/en/latest/api/
servers:
- url: '{base}/rest'
  description: The Bugzilla server
  variables:
    base:
      description: The base Bugzilla endpoint
      default: http://bmo.test
paths:
  '/bug':
    '$ref': './endpoints/bug.yaml'
  '/bug/{id}':
    '$ref': './endpoints/bug-by-id.yaml'
  '/bug/{id}/comment':
    '$ref': './endpoints/bug-comment.yaml'
  '/bug/{id}/history':
    '$ref': './endpoints/bug-history.yaml'
  '/whoami':
    '$ref': './endpoints/whoami.yaml'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-BUGZILLA-API-KEY
security:
  - ApiKeyAuth: []
