openapi: 3.0.2
info:
  title: Bugzilla OpenAPI
  description: OpenAPI definitions for Bugzilla's REST API
  version: 0.0.1
externalDocs:
  description: Bugzilla API Documentation
  url: https://bugzilla.readthedocs.io/en/latest/api/
servers:
- url: '{base}/rest'
  description: The Bugzilla server
  variables:
    base:
      description: The base Bugzilla endpoint
      default: http://bmo.test
paths:
  '/bug':
    '$ref': './endpoints/bug.yaml'
  '/bug/{id}':
    '$ref': './endpoints/bug-by-id.yaml'
  '/bug/{id}/comment':
    '$ref': './endpoints/bug-comment.yaml'
  '/bug/comment/tags/{tag}':
    '$ref': './endpoints/bug-comment-tag.yaml'
  '/bug/comment/{id}/tags':
    '$ref': './endpoints/bug-comment-tag-update.yaml'
  '/bug/{id}/history':
    '$ref': './endpoints/bug-history.yaml'
  '/bug/{id}/attachment':
    '$ref': './endpoints/bug-attachment.yaml'
  '/bug/attachment/{id}':
    '$ref': './endpoints/attachment.yaml'
  '/product':
    '$ref': './endpoints/product.yaml'
  '/product/{id}':
    '$ref': './endpoints/product-by-id.yaml'
  '/component':
    '$ref': './endpoints/component.yaml'
  '/component/{id}':
    '$ref': './endpoints/component-by-id.yaml'
  '/component/{product_name}/{component_name}':
    '$ref': './endpoints/component-by-name.yaml'
  '/whoami':
    '$ref': './endpoints/whoami.yaml'
  '/version':
    '$ref': './endpoints/version.yaml'
  '/extensions':
    '$ref': './endpoints/extensions.yaml'
  '/timezone':
    '$ref': './endpoints/timezone.yaml'
  '/time':
    '$ref': './endpoints/time.yaml'
  '/parameters':
    '$ref': './endpoints/parameters.yaml'
  '/last_audit_time':
    '$ref': './endpoints/last_audit_time.yaml'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-BUGZILLA-API-KEY
security:
  - ApiKeyAuth: []
