get:
  summary: Search for products
  operationId: searchProducts
  parameters:
    - in: query
      name: ids
      schema:
        type: array
        items:
          type: string
    - in: query
      name: names
      schema:
        type: array
        items:
          type: string
    - in: query
      name: type
      schema:
        type: array
        items:
          '$ref': '../types/product.yaml#/ProductType'
    - name: exclude_fields
      in: query
      description: Fields to be excluded from the results
      schema:
        type: array
        items:
          type: string
      style: form
      explode: false
    - name: include_fields
      in: query
      description: Fields to be included in the results
      schema:
        type: array
        items:
          type: string
      style: form
      explode: false
  responses:
    '200':
      description: Successful operation
      content:
        application/json:
          schema:
            '$ref': '../types/product.yaml#/GetProductResponse'

post:
  summary: Create a product
  operationId: createProduct
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../types/product.yaml#/CreateProduct'
  responses:
    '200':
      description: Successful operation
      content:
        application/json:
          schema:
            title: CreateProductResponse
            type: object
            properties:
              id:
                type: integer
