name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          architecture: x64

      - name: Setup dependencies
        run: pip3 install openapi-spec-validator

      - name: Validate Spec
        run: openapi-spec-validator core.yaml

