name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install openapi-generator
        run: sudo npm install @openapitools/openapi-generator-cli -g

      - name: Validate
        run: openapi-generator validate -i core.yaml
